App/user/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, PasswordField
from wtforms.validators import DataRequired, EqualTo, Length


class LoginForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    
    
class RegisterForm(FlaskForm):
    user_len_warn = "Username can't be longer than 25 characters"
    pass_len_warn = "Passwords must be similiar"
    
    username = StringField('Username',
                           validators=[
                               DataRequired(),
                                Length(max=25,message=user_len_warn)
                                ])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('Password',
                              validators=[DataRequired(),
                                    EqualTo('password',
                                            message=pass_len_warn)
                                    ])
    
    
    
    

App/user/__init__.py
from flask.blueprints import Blueprint


user_bp = Blueprint('user', __name__, template_folder='templates', url_prefix='/user')

from . import views, forms

App/user/views.py
from flask import render_template, request, flash, redirect, url_for
from flask_login import login_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash

from . import user_bp
from .forms import LoginForm, RegisterForm
from ..models import User
from .. import login_manager, db


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=user_id).first()

@user_bp.route('login/', methods=['GET', 'POST'])
def login():
    """Renders page with login form.
    Handles such methods as:
    GET - page entry, form creation
    POST - login user if password hash correct

    Returns:
        Html login page
    """
    form = LoginForm()
        
    if request.method == 'POST':
            user = User.query.filter_by(
                username=form.data['username']).first()
            if user:
                if check_password_hash(user.password,
                                       form.data['password']):
                    login_user(user) 
                    flash('You successfully logged in!', 'success')
                    return redirect(url_for('main_page.index'))
            else:
                flash('Wrong username or password...', 'error')
                return redirect(url_for('main_page.index'))
        
    return render_template('login.html', form=form)

@user_bp.route('register/', methods=['GET', 'POST'])
def register():
    """Renders page with register form.
    Handles such methods as:
    GET - page entry, form creation
    POST - registers user, adds him to DB

    Returns:
        Html register page
    """
    form = RegisterForm()
    if request.method == 'POST':
        username = form.data['username']
        password = generate_password_hash(form.data['password']) 
        user = User.query.filter_by(
                username=form.data['username']).first()
        if not user:
            user = User(username=username, password=password)
            db.session.add(user)
            db.session.commit()
            
            flash('You have successfully registered', 'success')
            return redirect(url_for('main_page.index'))
        else:
            flash('Username already taken by someone...', 'error')
            return redirect(url_for('main_page.index'))
        
    return render_template('register.html', form=form)


@user_bp.route('/logout')
def logout():
    """Redirecting to index page.

    Returns:
        redirection to index page
    """
    flash('You logged out', 'success')
    logout_user()
    return redirect(url_for('main_page.index'))

App/user/templates/base_login.html
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% block stylesheet %} {% endblock %}">
    </head>
    <body>
        {% block body %}{% endblock %}
        <script src="{% block script %}{% endblock %}" async defer></script>
    </body>
</html>

App/user/templates/login.html
{% extends "base_login.html" %}

{% block body %}
    <form id='login-form' method='POST' action="{{ url_for('user.login')}}">
        {{form.csrf_token}}
        {{form.username.label}}
        {{form.username}}<br>
        {{form.password.label}}
        {{form.password}}<br>
        <button type='submit' id='login-submit'>Enter</button>
    </form>
    <p>
        Haven't registered yet? <a href="{{ url_for('user.register')}}">register now</a>
    </p>
{% endblock %}

App/user/templates/register.html
{% extends 'base_login.html' %}

{% block body %}
    <form id='login-form' method='POST' action="{{ url_for('user.register')}}">
        {{form.csrf_token}}
        {{form.username.label}}
        {{form.username}}<br>
        {{form.password.label}}
        {{form.password}}<br>
        {{form.password2.label}}
        {{form.password2}}<br>
        <button type='submit' id='register-submit'>Enter</button>
    </form>
{% endblock %}